/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');

// Configure Angular `environment.ts` file path
const targetPath = './src/environments/environment.ts';
// Load node modules
const colors = require('colors');
require('dotenv').config();
// `environment.ts` file structure

const envConfigFile = `
// This file is auto-generated by 'set-env.ts'.  Adjust any new variables there or configure variables with a .env file.

export const environment = {
	${getAPISettingsVars()}
};
`;
console.log(
	colors.magenta(
		'The file `environment.ts` will be written with the following content: \n',
	),
);
console.log(colors.grey(envConfigFile));
fs.writeFile(
	targetPath,
	envConfigFile,
	function (err: NodeJS.ErrnoException | null) {
		if (err) {
			throw new Error('Failed to write environment file');
		} else {
			console.log(
				colors.magenta(
					`Angular environment.ts file generated correctly at ${targetPath} \n`,
				),
			);
			process.exit();
		}
	},
);

// Unwraps and installs API_SETTINGS.
function getAPISettingsVars() {
	let vars = '';

	try {
		const map = JSON.parse(process.env.API_SETTINGS || '{}');

		if (map['localhost']) {
			vars += `exclusive: ${map['localhost'].length === 1 ? true : false},\n`;

			const settings = JSON.stringify(map['localhost'])
				? `JSON.parse('${JSON.stringify(map['localhost'])}')`
				: undefined;
			vars += `\tapiSettings: ${settings},\n`;

			const host = map['localhost']?.[0].endpoint
				? `'${map['localhost']?.[0].endpoint}'`
				: undefined;
			vars += `\tapiUrl: ${host},\n`;

			const org = map['localhost']?.[0].organizationId
				? `'${map['localhost']?.[0].organizationId}'`
				: undefined;
			vars += `\torganizationId: ${org},\n`;

			const production = process.env.PRODUCTION || false;
			vars += `\tproduction: ${production},\n`;

			const locale = `'${map['localhost']?.[0].locale || 'en-US'}'`;
			vars += `\tlocale: ${locale},`;

			const wppOpenParentOrigin = `'${map['localhost']?.[0].wppOpenParentOrigin || ''}'`;
			vars += `\twppOpenParentOrigin: ${wppOpenParentOrigin},\n`;

			const wppOpenDebug = `'${map['localhost']?.[0].wppOpenDebug || ''}'`;
			vars += `\twppOpenDebug: ${wppOpenDebug}\n`;

			return vars;
		} else {
			throw new Error('Bad settings map.');
		}
	} catch {
		return `
			exclusive: window['exclusive'],
			apiSettings: window['organizations'],
			apiUrl: window['apiUrl'],
			organizationId: window['organizationId'],
			production: window['production'],
			locale: window['locale'],
			wppOpenParentOrigin: window['wppOpenParentOrigin'],
			wppOpenDebug: window['wppOpenDebug']
		`;
	}
}
